release-schema.json: rename AwardCriterionNumber to CriterionNumber a…
open-contracting-extensions/ocds_awardCriteria_extension pull request #5
Opened 2023-04-25 15:38 UTC by odscjen

…s per issue [#199](https://github.com/open-contracting/ocds-extensions/issues/199#issuecomment-1506052707) and PR comment in https://github.com/open-contracting-extensions/ocds_selectionCriteria_extension/pull/5#discussion_r1162191134

2023-04-27 05:20 UTC, duncandewhurst requested changes

2023-04-27 05:20 UTC, duncandewhurst commented on README.md
> +* Rename AwardCriterionNumber to `CriterionNumber` and update descriptions in "criterionThreshold.csv"
Based on the [bids extension changelog](https://extensions.open-contracting.org/en/extensions/bids/master/#changelog), codelist CSV names should be in backticks:

```suggestion
* Rename AwardCriterionNumber to `CriterionNumber` and update descriptions in `criterionThreshold.csv`
```

2023-06-07 04:15 UTC, duncandewhurst approved these changes

2023-06-07 19:47 UTC, jpmckinney commented on README.md
> +* Rename AwardCriterionNumber to `CriterionNumber` and update descriptions in `criterionThreshold.csv`
```suggestion
* Add requests to participate to `criterionThreshold.csv` code descriptions.
* Generalize AwardCriterionNumber to `CriterionNumber` for reuse in other extensions.
```

2023-06-07 19:48 UTC, jpmckinney approved these changes

2023-06-07 19:48 UTC, merged